apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-authentication
spec:
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      volumes:
      - name: environment
        configMap:
          name: authentication-environment
          items:
          - key: .env
            path: .env
      containers:
      - name: authentication
        imagePullPolicy: Never
        image: {{ .Values.repository }}:{{ .Values.version }}
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
        volumeMounts:
        - name: environment
          mountPath: /home/app/.env
          subPath: .env
        ports:
        - containerPort: 3000

