apiVersion: v1
kind: ConfigMap
metadata:
  name: authentication-environment
data:
  .env: |
    SECRET=verysecret
    TOKEN_EXPIRE=3600
    REDIS_ADDR={{ .Release.Name }}-redis-master.{{ .Release.Name }}.svc.cluster.local:6379
