name: Docker Image CI

on:
  push:
    tags: 
      - "*.*.*"
  workflow_dispatch:
   
env: 
  IMAGE_NAME: ghcr.io/jlighter/deless/authentitcation
  
jobs:
  build:
    name: Build docker image and deploy to github registry
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:$GITHUB_REF_NAME
    - name: Login to github registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username JLighter --password-stdin
    - name: Deploy to github registry
      run: docker push $IMAGE_NAME:$GITHUB_REF_NAME
